import json
import os

with open(r'e:\ThanhNhan\TL_new(14_4)\notenooks_new\compare_4_models_fixed.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find the cell and replace it
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and len(cell['source']) > 0 and 'import kagglehub\n' in cell['source'][0]:
        cell['source'] = [
            "import kagglehub\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import os\n",
            "import unicodedata\n",
            "from pathlib import Path\n",
            "\n",
            "DATA_DIR = Path('/content/data')\n",
            "DATA_DIR.mkdir(parents=True, exist_ok=True)\n",
            "MERGED_PATH = DATA_DIR / 'merged_datasets.csv'\n",
            "\n",
            "print(\"📥 Đang tải 4 datasets từ Kaggle...\")\n",
            "df_list = []\n",
            "\n",
            "# Dataset 1\n",
            "try:\n",
            "    path1 = kagglehub.dataset_download(\"phngnguynthu1803/vietnamese-fake-news-dataset\")\n",
            "    for file in sorted(os.listdir(path1)):\n",
            "        if not file.endswith('.csv'): continue\n",
            "        try:\n",
            "            temp = pd.read_csv(os.path.join(path1, file), encoding='utf-8')\n",
            "            temp.rename(columns={'news': 'text', 'content': 'text'}, inplace=True)\n",
            "            if 'real' in file.lower():   temp['label'] = 0\n",
            "            elif 'fake' in file.lower(): temp['label'] = 1\n",
            "            else:\n",
            "                print(f\"   ⚠️ Bỏ qua '{file}' — không xác định nhãn\")\n",
            "                continue\n",
            "            if 'text' in temp.columns:\n",
            "                df_list.append(temp[['text', 'label']].dropna())\n",
            "                print(f\"   ✅ DS1/{file}: {len(temp):,} mẫu\")\n",
            "        except: pass\n",
            "except Exception as e: print(f\"❌ DS1: {e}\")\n",
            "\n",
            "# Dataset 2\n",
            "try:\n",
            "    path2 = kagglehub.dataset_download(\"chuynvinquc/fakenewvn\")\n",
            "    for fname in [f for f in os.listdir(path2) if f.endswith('.csv')]:\n",
            "        temp = pd.read_csv(os.path.join(path2, fname), encoding='utf-8')\n",
            "        temp.rename(columns={'post_message': 'text'}, inplace=True)\n",
            "        if 'text' in temp.columns and 'label' in temp.columns:\n",
            "            temp['label'] = pd.to_numeric(temp['label'], errors='coerce')\n",
            "            temp.dropna(subset=['label'], inplace=True)\n",
            "            temp['label'] = temp['label'].astype(int)\n",
            "            df_list.append(temp[['text', 'label']])\n",
            "            print(f\"   ✅ DS2/{fname}: {len(temp):,} mẫu\")\n",
            "except Exception as e: print(f\"❌ DS2: {e}\")\n",
            "\n",
            "# Dataset 3\n",
            "try:\n",
            "    path3 = kagglehub.dataset_download(\"goumanguyen/vietnamese-fake-news-dataset-pbl7\")\n",
            "    for root, _, files in os.walk(path3):\n",
            "        for file in sorted(files):\n",
            "            if not file.endswith('.csv'): continue\n",
            "            try:\n",
            "                temp = pd.read_csv(os.path.join(root, file), encoding='utf-8')\n",
            "                temp.rename(columns={'Maintext':'text','maintext':'text','Label':'label'}, inplace=True)\n",
            "                if 'text' in temp.columns and 'label' in temp.columns:\n",
            "                    if temp['label'].dtype == object:\n",
            "                        temp['label'] = temp['label'].map(\n",
            "                            {'Real':0,'real':0,'Fake':1,'fake':1,'TIN THẬT':0,'TIN GIẢ':1})\n",
            "                    temp['label'] = pd.to_numeric(temp['label'], errors='coerce')\n",
            "                    temp.dropna(subset=['label','text'], inplace=True)\n",
            "                    temp['label'] = temp['label'].astype(int)\n",
            "                    df_list.append(temp[['text','label']])\n",
            "                    print(f\"   ✅ DS3/{file}: {len(temp):,} mẫu\")\n",
            "            except: pass\n",
            "except Exception as e: print(f\"❌ DS3: {e}\")\n",
            "\n",
            "# Dataset 4\n",
            "try:\n",
            "    path4 = kagglehub.dataset_download(\"leviettrieu369/vietnamese-medical-fake-news-dataset\")\n",
            "    for fname in [f for f in os.listdir(path4) if f.endswith('.csv')]:\n",
            "        temp = pd.read_csv(os.path.join(path4, fname), encoding='utf-8')\n",
            "        temp.rename(columns={'normalized_content':'text','is_fake':'label'}, inplace=True)\n",
            "        if 'label' in temp.columns and 'text' in temp.columns:\n",
            "            bool_map = {True:1,False:0,'True':1,'False':0,'TRUE':1,'FALSE':0,1:1,0:0}\n",
            "            temp['label'] = temp['label'].map(bool_map)\n",
            "            temp.dropna(subset=['label','text'], inplace=True)\n",
            "            temp['label'] = temp['label'].astype(int)\n",
            "            df_list.append(temp[['text','label']])\n",
            "            print(f\"   ✅ DS4/{fname}: {len(temp):,} mẫu\")\n",
            "except Exception as e: print(f\"❌ DS4: {e}\")\n",
            "\n",
            "# Gộp & làm sạch\n",
            "df_raw = pd.concat(df_list, ignore_index=True)\n",
            "df_raw['text'] = df_raw['text'].apply(lambda x: unicodedata.normalize('NFC', str(x)))\n",
            "df_raw.drop_duplicates(subset=['text'], keep='first', inplace=True)\n",
            "df_raw = df_raw[df_raw['text'].str.len() >= 30]\n",
            "df_raw = df_raw[df_raw['label'].isin([0, 1])]\n",
            "df = df_raw.sample(frac=1, random_state=42).reset_index(drop=True)\n",
            "\n",
            "df.to_csv(MERGED_PATH, index=False, encoding='utf-8-sig')\n",
            "print(f\"\\n💾 Đã lưu: {MERGED_PATH}\\n\")\n",
            "\n",
            "# ── Thống kê tổng quan ──\n",
            "counts = df['label'].value_counts().sort_index()\n",
            "print(\"\\n\" + \"=\"*55)\n",
            "print(\"📊 THỐNG KÊ DATASET CHUNG\")\n",
            "print(\"=\"*55)\n",
            "print(f\"  Tổng mẫu         : {len(df):,}\")\n",
            "print(f\"  Tin thật (0)     : {counts.get(0,0):,}  ({counts.get(0,0)/len(df)*100:.1f}%)\")\n",
            "print(f\"  Tin giả  (1)     : {counts.get(1,0):,}  ({counts.get(1,0)/len(df)*100:.1f}%)\")\n",
            "print(\"=\"*55)\n",
            "print(\"✅ Dataset sẵn sàng cho cả 4 mô hình!\")\n"
        ]
        break

with open(r'e:\ThanhNhan\TL_new(14_4)\notenooks_new\compare_4_models_fixed.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
